### ISSUE TITLE
No change detected with js-array

### ISSUE THREAD

**Issue by mbuehrig** [WebReflection/wrist#2]
I try to watch an array in the JS to determine if there was a change, but It doesn't trigger with an array. With a normal string value there is no problem. But if just the content of the array is updated it doesn't observe the change. Is this broken, am I stupid or is this just not a feature?

**Comment by WebReflection** [comment]
this library targets mostly the DOM. If you want to intercept changes I suggest you to have a look at [introspected](https://github.com/WebReflection/introspected)

**Comment by mbuehrig** [comment]
Ok thanks. I'll take a look. BTW: Amazing work
